namespace TbsCrossPlatform.Models.Enums
{
    public enum BuildingEnum
    {
        Site = 0,
        Woodcutter = 1,
        ClayPit,
        IronMine,
        Cropland,
        Sawmill,
        Brickyard,
        IronFoundry,
        GrainMill,
        Bakery,
        Warehouse,
        Granary,
        Blacksmith, // Deprecated
        Smithy,
        TournamentSquare,
        MainBuilding,
        RallyPoint,
        Marketplace,
        Embassy,
        Barracks,
        Stable,
        Workshop,
        Academy,
        Cranny,
        TownHall,
        Residence,
        Palace,
        Treasury,
        TradeOffice,
        GreatBarracks,
        GreatStable,
        CityWall,
        EarthWall,
        Palisade,
        StonemasonsLodge,
        Brewery,
        Trapper,
        HerosMansion,
        GreatWarehouse,
        GreatGranary,
        WW,
        HorseDrinkingTrough,
        StoneWall,
        MakeshiftWall,
        CommandCenter,
        Waterworks,
        Hospital,
    }
}