namespace TravBotSharp.Files.Helpers
{
    public static class Classificator
    {
        public enum BuildingEnum
        {
            Site = 0,
            Woodcutter = 1,
            ClayPit,
            IronMine,
            Cropland,
            Sawmill,
            Brickyard,
            IronFoundry,
            GrainMill,
            Bakery,
            Warehouse,
            Granary,
            Blacksmith,
            Smithy,
            TournamentSquare,
            MainBuilding,
            RallyPoint,
            Marketplace,
            Embassy,
            Barracks,
            Stable,
            Workshop,
            Academy,
            Cranny,
            TownHall,
            Residence,
            Palace,
            Treasury,
            TradeOffice,
            GreatBarracks,
            GreatStable,
            CityWall,
            EarthWall,
            Palisade,
            StonemasonsLodge,
            Brewery,
            Trapper,
            HerosMansion,
            GreatWarehouse,
            GreatGranary,
            WW,
            HorseDrinkingTrough,
            StoneWall,
            MakeshiftWall,
            CommandCenter,
            Waterworks,
            Hospital,
        }

        public enum TroopsEnum
        {
            None,
            //Romans//,
            Legionnaire,
            Praetorian,
            Imperian,
            EquitesLegati,
            EquitesImperatoris,
            EquitesCaesaris,
            RomanRam,
            RomanCatapult,
            RomanChief,
            RomanSettler,
            //Teutons//,
            Clubswinger,
            Spearman,
            Axeman,
            Scout,
            Paladin,
            TeutonicKnight,
            TeutonRam,
            TeutonCatapult,
            TeutonChief,
            TeutonSettler,
            //Gauls//,
            Phalanx,
            Swordsman,
            Pathfinder,
            TheutatesThunder,
            Druidrider,
            Haeduan,
            GaulRam,
            GaulCatapult,
            GaulChief,
            GaulSettler,
            //Nature//,
            Rat,
            Spider,
            Snake,
            Bat,
            WildBoar,
            Wolf,
            Bear,
            Crocodile,
            Tiger,
            Elephant,
            //Natars//,
            Pikeman,
            ThornedWarrior,
            Guardsman,
            BirdsOfPrey,
            Axerider,
            NatarianKnight,
            Warelephant,
            Ballista,
            NatarianEmperor,
            Settler,
            //Egyptians//,
            SlaveMilitia,
            AshWarden,
            KhopeshWarrior,
            SopduExplorer,
            AnhurGuard,
            ReshephChariot,
            EgyptianRam,
            EgyptianCatapult,
            EgyptianChief,
            EgyptianSettler,
            //Huns//,
            Mercenary,
            Bowman,
            Spotter,
            SteppeRider,
            Marksman,
            Marauder,
            HunRam,
            HunCatapult,
            HunChief,
            HunSettler,
            //Hero
            Hero
        }
        public enum TribeEnum
        {
            Any = 0,
            Romans = 1, //1
            Teutons,
            Gauls,
            Nature,
            Natars,
            Egyptians, //6
            Huns, //7
        }
        public enum ServerVersionEnum
        {
            T4_4,
            T4_5
        }

        public enum MovementType
        {
            Reinforcement = 2,
            Attack,
            Raid
        }
        public enum VillTypeEnum
        {
            _9c = 1,
            _3456,
            _4446,
            _4536,
            _5346,
            _15c,
            _4437,
            _3447,
            _4347,
            _3547,
            _4356,
            _5436,
        }
    }
}
