namespace MainCore.Enums
{
    public enum HeroStatusEnums
    {
        Unknown,
        Home,
        Away,
        Dead,
        Regenerating,
        Reinforcing
    }

    public enum DifficultyEnums
    {
        Normal = 0,
        Hard = 1
    }

    public enum HeroItemEnums
    {
        None = 0,
        HelmetExperience1,
        HelmetExperience2,
        HelmetExperience3,
        HelmetRegeneration1,
        HelmetRegeneration2,
        HelmetRegeneration3,
        HelmetCulturePoints1,
        HelmetCulturePoints2,
        HelmetCulturePoints3,
        HelmetCavalry1,
        HelmetCavalry2,
        HelmetCavalry3,
        HelmetInfantry1,
        HelmetInfantry2,
        HelmetInfantry3,

        WeaponLegionnaire1,
        WeaponLegionnaire2,
        WeaponLegionnaire3,
        WeaponPraetorian1,
        WeaponPraetorian2,
        WeaponPraetorian3,
        WeaponImperian1,
        WeaponImperian2,
        WeaponImperian3,
        WeaponEquitesImperatoris1,
        WeaponEquitesImperatoris2,
        WeaponEquitesImperatoris3,
        WeaponEquitesCaesaris1,
        WeaponEquitesCaesaris2,
        WeaponEquitesCaesaris3,

        WeaponPhalanx1,
        WeaponPhalanx2,
        WeaponPhalanx3,
        WeaponSwordsman1,
        WeaponSwordsman2,
        WeaponSwordsman3,
        WeaponTheutatesThunder1,
        WeaponTheutatesThunder2,
        WeaponTheutatesThunder3,
        WeaponDruidrider1,
        WeaponDruidrider2,
        WeaponDruidrider3,
        WeaponHaeduan1,
        WeaponHaeduan2,
        WeaponHaeduan3,

        WeaponClubswinger1,
        WeaponClubswinger2,
        WeaponClubswinger3,
        WeaponSpearman1,
        WeaponSpearman2,
        WeaponSpearman3,
        WeaponAxeman1,
        WeaponAxeman2,
        WeaponAxeman3,
        WeaponPaladin1,
        WeaponPaladin2,
        WeaponPaladin3,
        WeaponTeutonicKnight1,
        WeaponTeutonicKnight2,
        WeaponTeutonicKnight3,

        Map1,
        Map2,
        Map3,
        Pennant1,
        Pennant2,
        Pennant3,
        Standard1,
        Standard2,
        Standard3,
        Spyglasses1, // Aren't in the game
        Spyglasses2, // Aren't in the game
        Spyglasses3, // Aren't in the game
        Pouch1,
        Pouch2,
        Pouch3,
        Shield1,
        Shield2,
        Shield3,
        Horn1,
        Horn2,
        Horn3,

        ArmorRegeneration1,
        ArmorRegeneration2,
        ArmorRegeneration3,
        ArmorScale1,
        ArmorScale2,
        ArmorScale3,
        ArmorBreastplate1,
        ArmorBreastplate2,
        ArmorBreastplate3,
        ArmorSegmented1,
        ArmorSegmented2,
        ArmorSegmented3,

        BootsRegeneration1,
        BootsRegeneration2,
        BootsRegeneration3,
        BootsMercenery1,
        BootsMercenery2,
        BootsMercenery3,
        BootsSpurs1,
        BootsSpurs2,
        BootsSpurs3,

        Horse1,
        Horse2,
        Horse3,

        Ointment,
        Scroll,
        Bucket,
        Tablets,
        Book,
        Artwork,
        SmallBandage,
        BigBandage,
        Cage,

        WeaponSlaveMilitia1,
        WeaponSlaveMilitia2,
        WeaponSlaveMilitia3,
        WeaponAshWarden1,
        WeaponAshWarden2,
        WeaponAshWarden3,
        WeaponKhopeshWarrior1,
        WeaponKhopeshWarrior2,
        WeaponKhopeshWarrior3,
        WeaponAnhurGuard1,
        WeaponAnhurGuard2,
        WeaponAnhurGuard3,
        WeaponReshephChariot1,
        WeaponReshephChariot2,
        WeaponReshephChariot3,

        WeaponMercenary1,
        WeaponMercenary2,
        WeaponMercenary3,
        WeaponBowman1,
        WeaponBowman2,
        WeaponBowman3,
        WeaponSteppeRider1,
        WeaponSteppeRider2,
        WeaponSteppeRider3,
        WeaponMarksman1,
        WeaponMarksman2,
        WeaponMarksman3,
        WeaponMarauder1,
        WeaponMarauder2,
        WeaponMarauder3,

        Wood,
        Clay,
        Iron,
        Crop
    }
}