name: BuildFlow

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Install dependencies
      run: dotnet restore TbsCrossPlatform
      
    - name: Build
      run: |
        dotnet publish TbsCrossPlatform -p:PublishProfile=WindowsProfile
        ls TbsCrossPlatform\bin\publish\
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TBS-Build-Windows-${{ github.sha }}
          path: TbsCrossPlatform\bin\publish\Windows
          if-no-files-found: error

      - name: Comment on PR when success
        uses: actions/github-script@0.3.0
        if: |
          github.event_name == 'pull_request' && success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: "Congratulation this commit was built successfully. Check detail [here](https://github.com/Erol444/TravianBotSharp/actions/runs/${{ github.run_id }}?check_suite_focus=true)" });

      - name: Comment on PR when fail
        uses: actions/github-script@0.3.0
        if: |
          github.event_name == 'pull_request' && failure()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: "There is error while building this commit. Check detail [here](https://github.com/Erol444/TravianBotSharp/actions/runs/${{ github.run_id }}?check_suite_focus=true)" });

