name: reactflow

on:
  push:

jobs:
  build_react:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo' 
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'
      - name: Build dotnet
        run: dotnet build --configuration Release
      - name: Build dotnet
        run: dotnet publish TbsReact/TbsReact.csproj /p:PublishProfile=TbsReact/Properties/PublishProfiles/Linux.pubxml